version: '2.1'
orbs:
  slack: circleci/slack@4.2.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Destroy environments
          command: |
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7}
workflows:
  test-and-deploy:
    jobs:
      - deploy
