version: '2.1'
orbs:
  slack: circleci/slack@4.2.0
  aws-cli: circleci/aws-cli@1.3.1
commands:
  destroy-environment:
    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
    steps:
      - aws-cli/install
      - run:
          name: Destroy environments
          command: |
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID:0:7}
jobs:
  configure-infrastructure:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "58:13:d8:a6:51:ab:82:23:72:5a:af:ac:35:ea:97:dc:78:03:3b:f3"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y
            curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
            sudo apt install -y tar gzip curl python3 nodejs ansible
            sudo npm install pm2 -g
      - run:
          name: Configure server
          command: |
            # Your code here
            exit 1
      - destroy-environment  
workflows:
  test-and-deploy:
    jobs:
      - configure-infrastructure
